
services:
  database:
    image: mysql:8.0
    container_name: database
    platform: linux/amd64
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=codetest
      - MYSQL_USER=codetest
      - MYSQL_PASSWORD=swordfish
    ports:
      - "3306:3306"
    restart: always

  mysql-schema:
    image: mysql-schema
    build: images/mysql-schema
    command: ["python", "mysql_schema.py"]
    depends_on:
      - database


  data-ingest:
    image: data-ingest
    build: images/data-ingest
    command: ["python", "data_ingest.py"]
    volumes:
    - ./data:/app/data
    depends_on:
      - database

  summary-output:
    image: summary-output
    build: images/summary-output
    command: ["python", "summary_output.py"]
    volumes:
    - ./data:/app/data
    depends_on:
      - database
